"""

Revision ID: 3138f0441eb9
Revises: 9db728ad4371
Create Date: 2021-04-12 17:19:55.375421

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3138f0441eb9'
down_revision = '9db728ad4371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_token_id_tokens', 'tokens', ['token_id'], ['id'])
        batch_op.drop_column('admin')

    op.create_table('tokens',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('token', sa.VARCHAR(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
