"""empty message

Revision ID: 31cffac1263b
Revises: db114208b030
Create Date: 2021-03-25 18:08:08.709251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cffac1263b'
down_revision = 'db114208b030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
