"""

Revision ID: 9db728ad4371
Revises: b8edf353543c
Create Date: 2021-04-11 19:50:21.268511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db728ad4371'
down_revision = 'b8edf353543c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_phone_number'), ['phone_number'])
        batch_op.create_foreign_key(batch_op.f('fk_users_rank_id_ranks'), 'ranks', ['rank_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_token_id_tokens'), 'tokens', ['token_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_token_id_tokens'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_rank_id_ranks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_users_phone_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    # ### end Alembic commands ###
