"""

Revision ID: a14f10c51cb6
Revises: 31cffac1263b
Create Date: 2021-03-26 19:51:06.214945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14f10c51cb6'
down_revision = '31cffac1263b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('title', sa.String(), nullable=True))
    op.add_column('advertisements_to_interests', sa.Column('interests', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'advertisements_to_interests', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements_to_interests', 'interests', ['interests'], ['id'])
    op.drop_column('advertisements_to_interests', 'interests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements_to_interests', sa.Column('interests', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'advertisements_to_interests', type_='foreignkey')
    op.create_foreign_key(None, 'advertisements_to_interests', 'interests', ['interests'], ['id'])
    op.drop_column('advertisements_to_interests', 'interests')
    op.drop_column('advertisements', 'title')
    # ### end Alembic commands ###
