"""

Revision ID: a14f10c51cb6
Revises: 31cffac1263b
Create Date: 2021-03-26 19:51:06.214945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14f10c51cb6'
down_revision = '31cffac1263b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rank', sa.Unicode()))
    op.add_column('users', sa.Column('position', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rank')
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
